server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://${SERVICE_NAME:localhost}:9411/zipkin/

logging:
  level:
    io.fullstacklabs: INFO
    org.springframework.web.servlet.DispatcherServlet: TRACE

test.name: YupWorking