server:
  port: ${SERVER_PORT:8082}

spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  cloud:
    vault:
      token: s.TWlHxlypkKikxuc5BD2Et6RO
      scheme: http

logging:
  level:
    io.fullstacklabs: INFO
    org.springframework.web.servlet.DispatcherServlet: TRACE

test.name: Working