spring:
  application:
    name: eureka-server
  rabbitmq:
    port: 5672
    host: rabbit
server:
  port: ${SERVER_PORT:8761}



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

