server:
  port: ${SERVER_PORT:8083}

spring:
  zipkin:
    base-url: http://${SERVICE_NAME:localhost}:9411/zipkin/

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/