server:
  port: ${SERVER_PORT:8083}

spring:
  zipkin:
    base-url: http://$zipkin:9411/zipkin/
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/