server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

spring:
  zipkin:
    base-url: http://${SERVICE_NAME:localhost}:9411/
    enabled: true
